test: Pull boto client creation into functions
Fixes the issue where commands like `pytest -m 'not infrastructure'
infra/tests` fails because it tries to create a boto3 client when
looking for test markers:

> botocore.exceptions.NoRegionError: You must specify a region.